Bugfix: Session onDelete
Error: All sessions were deleted when trying to delete one.
Cause: Due to cascade all on users all sessions sharing the same users were deleted.